### ISSUE TITLE
Negative values are not shown in Xcode 12 and through error " Invalid frame dimension (negative or non-finite)"

### ISSUE THREAD

**Issue by shipra-ios** [dawigr/BarChart#1]
I have run this project in Xcode 12 and It through below error in Swift UI.

SelectableBarChartExample-iOS[31888:477881] [SwiftUI] Invalid frame dimension (negative or non-finite).

![Screenshot 2021-01-08 at 7 09 29 PM](https://user-images.githubusercontent.com/56666349/104021618-17960380-51e5-11eb-86ba-b18375df87f8.png)

**Comment by dawigr** [comment]
Just fixed the issue in 3.1.0. All examples updated as well.

Thanks for opening the issue!
